# Generated by Django 6.0.5 on 2026-05-22 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
