# Generated by Django 6.0.5 on 2026-05-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_galleryimage_delete_contactmessage_and_more'),
    ]

    operations = [
    ]
