# Generated by Django 6.0.5 on 2026-05-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_add_slug_to_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.news'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.project'),
        ),
    ]
