# Generated by Django 4.2.30 on 2026-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_category_options_alter_galleryimage_options_and_more'),
        ('website', '0009_add_utils_no_schema_change'),
    ]

    operations = [
    ]
